name: Generate Release and Upload APK

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '12'
          distribution: 'adopt'

      - name: Build and package APK
        run: ./gradlew assembleRelease

      - name: Generate release notes
        id: release-notes
        run: echo "::set-output name=notes::$(cat notes.txt)"

      - name: Create release draft
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: true
          body: ${{ steps.release-notes.outputs.notes }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_PAT }}
        
      - name: Upload APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: MyApp-Release.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_PAT }}
